name = "aulbilim-media-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "aulbilim-media"

[vars]
FIREBASE_PROJECT_ID = "admin-aul-bilim"
PUBLIC_MEDIA_BASE_URL = "https://pub-fab6b6cfe128465294dac297e02ccd05.r2.dev"
